### PR TITLE
Support for lein-ring plugin (run with Run button)

### PR DESCRIPTION
**Pull request by auwerk**
'Run' button is now able to start ring server for projects using lein-ring plugin;

### CODE REVIEW

**Comment by oakes** [comment]
I haven't had a chance to test it, but I wonder if it may be problematic for projects like [the clojurescript template](https://github.com/oakes/Nightcode/blob/master/src/clojure/leiningen/new/web_clojurescript/project.clj) which have a `:ring` declaration in the project.clj but still rely on the normal lein run command to run. Maybe they don't even need that declaration, come to think of it...

**Comment by auwerk** [comment]
I think they can use both for two separate ways to run: if you start it with `lein run`, it uses `:main` and if `lein ring server` it uses handler from `:ring` hashmap to start ring plugin. So, I think that necessity of `:main` depends on the application code itself (if it relies on it's own main function or not).

**Comment by auwerk** [comment]
I've added `(nil? :main)` check to `ring-project?` function.

**Comment by oakes** [comment]
Thanks very much!

**Pull request merged**
